sudo: required
services:
  - docker
before_install:
  - docker build -t tsvety/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tsvety/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker"
   env: "Docker-env"
   bucket_name: "elasticbeanstalk-us-east-1-104599568897"
   bucket-path: "docker"
   on: 
     branch: master
   access_key_id: "$AWS_SECRET_KEY"
   secret_access_key: "$AWS_SECRET_KEY"
